apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-k4fq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/bootstrap/integration-e2e-tenant/integ-app-gwkd/devfile-sample-python-basic-k4fq@sha256:b71ee4fd81ad5a54dc7f7be305f820960b8bdd8549155157060c02ab2b998d5a
        name: my-python
        resources: {}
status: {}
